import { Inter } from 'next/font/google'
import "../styles/globals.css"
import Footer from '@/components/Footer'
import Nav from '@/components/Nav'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Nav />
      <body className={inter.className}>{children}
      <Footer />
      </body>
      
    </html>
  )
}
